#!/usr/bin/python3

print('Content-type:text/html\n\n')
print('<html>')
print('<head>')
print('<title>Remove Page</title>')
print('</head>')
print('<body>')
print('<link rel="stylesheet" href="form-style.css">')
print('<form action="add_customer.cgi" method="post">')
print('<h2 align="center">Add Customer</h2>')
print('<p>New name: <input type="text" name="name"/></p>')
print('<p>New email: <input type="text" name="email"/></p>')
print('<p>New phone: <input type="text" name="phone"/></p>')
print('<p>New address: <input type="text" name="address"/></p>')
print('<p><input type="submit" value="Submit"/></p>')
print('</form>')
print('</body>')
print('</html>')