#!/usr/bin/python3 

print('Content-type:text/html\n\n')
print('<html>')
print('<head>')
print('<title>Form Product Page</title>')
print('</head>')
print('<body>')
print('<link rel="stylesheet" href="form-style.css">')
print('<form action="add_product.cgi" method="post">')
print('<h2 align="center">Add Product</h2>')
print('<p>New sku: <input type="text" name="sku"/></p>')
print('<p>New name: <input type="text" name="name"/></p>')
print('<p>New description: <input type="text" name="description"/></p>')
print('<p>New price: <input type="text" name="price"/></p>')
print('<p>New ean: <input type="text" name="ean"/></p>')
print('<p><input type="submit" value="Submit"/></p>')
print('</body>')
print('</html>')