#!/usr/bin/python3 

print('Content-type:text/html\n\n')
print('<html>')
print('<head>')
print('<title>Form Order Page</title>')
print('</head>')
print('<body>')
print('<link rel="stylesheet" href="form-style.css">')
print('<form action="add_order.cgi" method="post">')
print('<h2 align="center">Add Order</h2>')
print('<p>Order for (cust_no): <input type="text" name="cust_no"/></p>')
print('<p>Product (sku): <input type="text" name="sku"/></p>')
print('<p>Quantity: <input type="text" name="quantity"/></p>')
print('<p>Employee (ssn): <input type="text" name="ssn"/></p>')
print('<p>Date (yy-mm-dd): <input type="text" name="date"/></p>')
print('<p><input type="submit" value="Submit"/></p>')
print('</body>')
print('</html>')